name: OpenAI Proxy

on:
  repository_dispatch:
    types: [openai-query]

jobs:
  openai_proxy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: OpenAI Query
      run: |
        curl -X POST https://api.openai.com/v1/engines/davinci/completions \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
        -d "$PAYLOAD" > response.json
      env:
        PAYLOAD: ${{ github.event.client_payload }}

    - name: Respond
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: openai-response
        client-payload: '{"data":${{ steps.query.outputs.response }}}'
